name: CACHE_CLEAN

on:
  workflow_dispatch:
#   workflow_run:
#     workflows: ["RUN_BUILD"]
#     types:
#       - completed

permissions: write-all

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Projects
        uses: actions/checkout@main

      - name: Cache Clean
        run: gh cache delete --all
