name: BUILD_PRESET

on:
  workflow_run:
    workflows: ["AUTO_CLEAN"]
    types:
      - completed

  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: false
        required: false
        type: boolean

permissions: write-all

#CI任务
jobs:
  config:
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      #max-parallel: 3
      matrix:
        CONFIG: [RedmiAX6]
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [main]

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/run_build.yml
    with:
      #编译配置
      WRT_CONFIG: ${{matrix.CONFIG}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: RMAX6
      #默认WIFI名称
      WRT_SSID: OpenWrt
      #默认WIFI密码
      WRT_WORD: 415a9c4a
      #默认地址
      WRT_IP: 172.26.0.1
      #子网掩码
      WRT_MASK: 255.255.0.0
      #默认密码
      WRT_PW: root
      #源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      #源码名称
      WRT_SOURCE: ${{matrix.SOURCE}}
      #源码分支
      WRT_BRANCH: ${{matrix.BRANCH}}
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
